size: [400, 300]
order:
  - avatar
  - background
  - name
  - color1
  - icon1
  - color2
  - icon2
  - color3
  - icon3
  - color4
  - icon4
  - color5
  - icon5
  - color6
  - icon6

avatar:
  type: image
  path: example/nothing.png
  position: [230, 20]

background:
  type: image
  path: example/background.png

name:
  type: text
  font: example/arial.ttf
  size: 48
  position: [24, 222]

color1:
  type: image
  path: example/nothing.png
  position: [20, 45]

icon1:
  type: image
  path: example/nothing.png
  position: [20, 45]

color2:
  type: image
  path: example/nothing.png
  position: [74, 45]

icon2:
  type: image
  path: example/nothing.png
  position: [74, 45]

color3:
  type: image
  path: example/nothing.png
  position: [128, 45]

icon3:
  type: image
  path: example/nothing.png
  position: [128, 45]

color4:
  type: image
  path: example/nothing.png
  position: [20, 99]

icon4:
  type: image
  path: example/nothing.png
  position: [20, 99]

color5:
  type: image
  path: example/nothing.png
  position: [74, 99]

icon5:
  type: image
  path: example/nothing.png
  position: [74, 99]

color6:
  type: image
  path: example/nothing.png
  position: [128, 99]

icon6:
  type: image
  path: example/nothing.png
  position: [128, 99]